alias ngr="sudo systemctl restart nginx.service"
alias ngs="sudo systemctl stop nginx.service"
alias www="cd /var/www"
alias we="cd /etc/nginx/sites-enabled"
alias wa="cd /etc/nginx/sites-available"
alias ll="ls -al"
alias l="ls"
